Do not use feenableexcept/fedisableexcept on musl
musl does not provice feenableexcept and fedisableexcept. Those calls have
only been used on linux so far. This patch extends the #ifdef logic to only use
them on Linux if additionally glibc is used.

Fixes
src/3rdparty/PhysX/source/foundation/src/unix/PsUnixFPU.cpp:65:2: error: use of undeclared identifier 'fedisableexcept'; did you mean 'feraiseexcept'?
   65 |         fedisableexcept(FE_ALL_EXCEPT);
      |         ^~~~~~~~~~~~~~~
      |         feraiseexcept

Pick-to: 6.5 6.6
Change-Id: I035acb62e91e3719a966f223e1a398531cd00ad1
Reviewed-by: Jonas Karlsson <jonas.karlsson@qt.io>