PhysX: Fix breakage due to reinterpret_cast<SomeType*>(NULL) on musl
Use nullptr instead of reinterpret_cast. Musl does not define NULL as
int but nullptr.

error: reinterpret_cast from 'std::nullptr_t' to 'PxVehicleTireData *' is not allowed

Pick-to: 6.5 6.6
Change-Id: I11bf68c252afb9b7e35d08dfa119df9decca28ab
Reviewed-by: Jonas Karlsson <jonas.karlsson@qt.io>