PhysX: Fix breakage due to reinterpret_cast<SomeType*>(NULL) on musl
Use nullptr instead of reinterpret_cast. Musl does not define NULL as
int but nullptr.

error: reinterpret_cast from 'std::nullptr_t' to 'PxVehicleTireData *' is not allowed

Change-Id: I11bf68c252afb9b7e35d08dfa119df9decca28ab
Reviewed-by: Jonas Karlsson <jonas.karlsson@qt.io>
(cherry picked from commit 4c710d4b32f0e056cb0d700c7c6e703e61f979eb)
Reviewed-by: Qt Cherry-pick Bot <cherrypick_bot@qt-project.org>